### PR TITLE
should be 1.14

### PR DESCRIPTION
**Pull request by yehjames**

### CODE REVIEW

**Comment by imcaspar** [comment]
The dependency should be break if we set tensorboard==1.14.0 according https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/tools/pip_package/setup.py#L59
Something I missed? @yehjames

**Comment by yehjames** [comment]
Sorry, I should change both tensorflow-gpu and tensorboard to 1.14.0. Because I cannot run the script successfully in 1.13.0 until I upgrade TensorFlow to 1.14.0

**Comment by imcaspar** [comment]
thank you for the report!
Which script failed? Could you also provide the error message?

**Comment by ecrows** [comment]
Running the interactive conditional generation causes an exception as both module_wrapper and deprecation_wrapper don't exist in tensorflow=1.13.1

The dependency should be updated in the TPU and GPU requirements resepctively.

```
Traceback (most recent call last):
  File "scripts/interactive_conditional_samples.py", line 19, in <module>
    from tensorflow.python.util import module_wrapper as deprecation
ImportError: cannot import name 'module_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/interactive_conditional_samples.py", line 21, in <module>
    from tensorflow.python.util import deprecation_wrapper as deprecation
ImportError: cannot import name 'deprecation_wrapper'
```

**Pull request closed without merging**
